# Generated by Django 3.2.10 on 2024-08-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('BookId', models.BigIntegerField()),
                ('BookName', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
